# Generated by Django 3.1.1 on 2020-09-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=765)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TGM_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=100, null=True)),
                ('short_title', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_description', models.TextField(blank=True, null=True)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('condition_notes', models.CharField(blank=True, max_length=765, null=True)),
                ('edition', models.CharField(blank=True, max_length=200, null=True)),
                ('digitization_recommendation', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], max_length=20, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status', models.CharField(choices=[('complete', 'complete'), ('incomplete', 'incomplete'), ('review', 'review'), ('reviewed', 'reviewed')], max_length=20)),
                ('iona_holdings', models.CharField(blank=True, choices=[('original', 'original'), ('copy', 'copy'), ('original_copy', 'original and copy')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.original_source')),
                ('pub_places', models.ManyToManyField(blank=True, null=True, to='places.Location')),
                ('tgm_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tgm_genre')),
            ],
        ),
    ]
