# Generated by Django 3.1.1 on 2020-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_creator_role_item_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date_certainty',
            field=models.SmallIntegerField(choices=[(0, 'undated'), (1, 'cannot be verified'), (2, 'uncertain'), (3, 'possible'), (4, 'likely'), (5, 'verified')], default=0),
        ),
    ]
