# Generated by Django 3.1.1 on 2020-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_credit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
