# Generated by Django 3.1.1 on 2020-09-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='task',
            field=models.SmallIntegerField(verbose_name=[('created', 'created'), ('enhanced', 'enhanced'), ('reviewed', 'reviewed')]),
        ),
    ]
