# Generated by Django 3.1.1 on 2020-09-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200930_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='task',
            field=models.CharField(choices=[('created', 'created'), ('enhanced', 'enhanced'), ('reviewed', 'reviewed')], max_length=20),
        ),
    ]
