# Generated by Django 3.1.1 on 2020-09-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200930_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_creator',
            old_name='item',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='item_creator',
            old_name='organization',
            new_name='organizations',
        ),
        migrations.RenameField(
            model_name='item_creator',
            old_name='person',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='item_creator',
            old_name='role',
            new_name='roles',
        ),
    ]
