# Generated by Django 3.1.1 on 2020-11-12 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('organizations', '0001_initial'),
        ('inventory', '0010_auto_20200930_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_creator',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item_creator',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='item_creator',
            name='roles',
        ),
        migrations.AddField(
            model_name='item_creator',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='inventory.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_creator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='item_creator',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='inventory.creator_role'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item_creator',
            name='people',
        ),
        migrations.AddField(
            model_name='item_creator',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='people.person'),
        ),
    ]
