# Generated by Django 3.1.1 on 2020-11-24 03:04

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20201112_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
