# Generated by Django 3.1.1 on 2020-11-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20201124_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_creator',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
