# Generated by Django 3.1.1 on 2021-02-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_item_creator_pseudonym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_creator',
            old_name='people',
            new_name='person',
        ),
    ]
