# Generated by Django 3.1.1 on 2021-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210202_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oclc_permalink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='record_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('review', 'Review'), ('reviewed', 'Reviewed')], max_length=20),
        ),
    ]
