# Generated by Django 5.1.3 on 2024-11-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_auto_20210322_2041"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="dimensions",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="page_count",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="single_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
