# Generated by Django 5.1.3 on 2024-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0018_alter_creator_role_id_alter_credit_id_alter_item_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="pub_date_decade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="pub_date_descriptive",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="pub_year",
            field=models.IntegerField(
                blank=True,
                help_text="If only the year is known, record it here.",
                null=True,
                verbose_name="Year",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="pub_year_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="pub_year_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
