# Generated by Django 5.1.3 on 2025-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_item_pub_date_decade_item_pub_date_descriptive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional. Upload an image of the item.",
                null=True,
                upload_to="images/",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image_alt_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
