# Generated by Django 3.1.1 on 2021-01-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('continent', models.CharField(choices=[('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia')], max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('claims', models.ManyToManyField(blank=True, null=True, through='places.Claim', to='places.State')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='empire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.empire'),
        ),
        migrations.AddField(
            model_name='claim',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.state'),
        ),
        migrations.AddField(
            model_name='location',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='places.Region'),
        ),
    ]
