# Generated by Django 3.1.1 on 2021-01-29 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210127_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.state'),
            preserve_default=False,
        ),
    ]
