# Generated by Django 3.1.1 on 2021-02-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='genoname',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
