# Generated by Django 3.1.1 on 2021-02-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_location_genoname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='genoname',
            new_name='geoname',
        ),
    ]
