# Generated by Django 3.1.1 on 2021-03-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210206_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empire',
            name='claims',
            field=models.ManyToManyField(blank=True, through='places.Claim', to='places.State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='regions',
            field=models.ManyToManyField(blank=True, to='places.Region'),
        ),
    ]
