# Generated by Django 5.1.3 on 2024-11-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_auto_20210202_0003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
