# Generated by Django 3.1.1 on 2021-01-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210128_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='getty',
            new_name='wikipedia',
        ),
    ]
