# Generated by Django 3.1.1 on 2021-02-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20210128_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
