# Generated by Django 3.1.1 on 2021-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_membership_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='viaf',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
